project_name: "vae_12_5hz_dim2048_tts-sft" # speaker cond 换成单帧 ecapatdnn 特征
# exp_dir: "/home/node58_tmpdata2/kxxia/exp"
# exp_dir: "/mnt/nfs20/kxxia/data/exp"
exp_dir: "/mnt/xkx_data1/exp"

# log_dir:    exp_dir + project_name + logs
# output_dir: exp_dir + project_name + output_dir
# resume_dir: exp_dir + project_name + resume_dir

use_flash_attation: True

model:
  llm_model_name_or_path: "../Llama-3.2-1B-Instruct"
  latent_dim: 1024
tokenizer_path: "./tokenizer_dir"

audio_loss_weight: 1.0
end_loss_weight: 0.2
speaker_cond_kl_weight: 0.1
kl_loss_weight: 0.0

# start_checkpoint: "../epoch_33_step_153736.pt-vae_flow_tts_offline-ecapatdnn_v1"
# start_checkpoint: "/mnt/nfs20/kxxia/data/exp/vae_flow_tts_offline-ecapatdnn_v1/output/epoch_33_step_153736.pt"
start_checkpoint: "/mnt/xkx_data1/exp/vae_12_5hz_dim2048_tts/output/epoch_2_step_210000.pt"

# lr: 3e-5
lr: 5e-5
weight_decay: 1e-2
gradient_accumulation_steps: 1

scheduler: "cosine"
warmup_steps: 1_000
total_steps: 200_0000
save_interval: 5000

dataset:
  # meta_path: "./lirbitts_wav_train.jsonl"
  meta_path: "./train_lance-sft.lst"
  # meta_path: "/mnt/nfs20/kxxia/lance_backup/hq_170w_Mp3Data"
  # meta_path: "/mnt/xkx_data1/lance_data/hq_170w_Mp3Data"
  # meta_path: "/home/work_nfs19/kxxia/hq_170w_Mp3Data"
  spk_drop_prob: 0.1
  delay_frames: 1
  vae_config:
    config_file: "./configs/melvae/config_dim2048_12_5hz.json"
    hz: 12.5
    cpt_path: "../g_01800000_dim2048"

datapool:
  prefetch_size: 5000
  max_size: 5000
  num_workers: 32

  # prefetch_size: 5
  # max_size: 5
  # num_workers: 1

batch_generator:
  use_dynamic: true
  batch_size: 50
  # batch_size: 3
  max_token_length: 20000




